### ISSUE TITLE
Collapse PlanRequirements on sidebar when all requirements are met

### ISSUE THREAD

**Issue by aidigii** [acmutd/comet_planning#20] opened 2020-06-16 21:00 UTC
## Problem
The extensive list of plan requirements on the sidebar makes it difficult for users to navigate them. 

## Proposed Problem Solution
Once user has already met all the requirements for a specific category, that category automatically collapses to make more space for other courses.

**Comment by WillieCubed** [comment] 2020-07-27 16:02
Closing as duplicate of #6

**Closed by WillieCubed** 2020-07-27 16:02 UTC
Labels: enhancement
