### ISSUE TITLE
Handle dragging duplicate courses in degree plans

### ISSUE THREAD

**Issue by aidigii** [acmutd/comet_planning#19] opened 2020-06-16 20:44 UTC
## Problem
Upon the circumstance that course duplicates appear on the sidebar as a result of double majors, user might be confused by seeing these duplicates given they can only take one instance of a particular class. 

## Solution
Once user drags an instance of a duplicate on a semester board, the other duplicated instance disappears from the sidebar.

**Comment by WillieCubed** [comment] 2020-07-27 18:47
Closing as duplicate of #6

**Closed by WillieCubed** 2020-07-27 18:47 UTC
Labels: duplicate, enhancement
